WITH CAMAvsMLS AS (
  SELECT
    P.PARID,
    P.TAXYR,
    P.LUC,
    L.TAXDIST,
    L.CITYNAME
  FROM PARDAT P
  JOIN LEGDAT L
    ON L.TAXYR = P.TAXYR
   AND L.PARID = P.PARID
   AND L.CUR   = P.CUR
  WHERE P.CUR = 'Y'
    AND P.TAXYR = 2026
    AND P.DEACTIVAT IS NULL
    AND P.LUC IN ('510','550')
    AND L.TAXDIST IN (
      SELECT DISTCODE
      FROM RTDIST
      WHERE TAXYR = P.TAXYR
    )
),
-- Get one sale per parcel (use MIN SALEKEY if duplicates exist)
-- EXCLUDE sales linked to voided conveyances (CONVSTAT = 'V')
UniqueSales AS (
  SELECT 
    S.PARID,
    S.SALEDT,
    MIN(S.SALEKEY) AS SALEKEY,
    MAX(S.NOPAR) AS NOPAR,
    MAX(S.PRICE) AS PRICE,
    MAX(S.OLDOWN) AS OLDOWN,
    MAX(S.OWN1) AS OWN1
  FROM SALES S
  -- Join to CVTRAN: SALES.TRANSNO = CVTRAN.CONVEYNO
  LEFT JOIN CVTRAN CV
    ON CV.CONVEYNO = S.TRANSNO
  WHERE S.SALEVAL = 'P'
    AND S.SALEDT >= TO_DATE('2026-04-04','YYYY-MM-DD')
    AND S.SALEDT <  TO_DATE('2026-04-11','YYYY-MM-DD')
    AND S.PRICE IS NOT NULL
    -- Exclude voided conveyances (V = Void, keep C = Complete and others)
    AND (CV.CONVSTAT IS NULL OR CV.CONVSTAT <> 'V')
  GROUP BY S.PARID, S.SALEDT
)
SELECT DISTINCT
  PS.PARID,
  -- ADDITIONAL_PARCELS: Only parcels that share the SAME SALE (via SALEDT match)
  -- Also exclude voided conveyances from additional parcels
  CASE 
    WHEN A.NOPAR = 1 THEN NULL
    ELSE (
      SELECT LISTAGG(S2.PARID, ', ') WITHIN GROUP (ORDER BY S2.PARID)
      FROM SALES S2
      LEFT JOIN CVTRAN CV2 ON CV2.CONVEYNO = S2.TRANSNO
      WHERE S2.SALEDT = A.SALEDT
        AND S2.SALEVAL = 'P'
        AND S2.PARID <> PS.PARID
        AND S2.NOPAR = A.NOPAR
        AND S2.PRICE = A.PRICE
        AND (CV2.CONVSTAT IS NULL OR CV2.CONVSTAT <> 'V')
    )
  END AS ADDITIONAL_PARCELS,
  PS.TAXYR,
  PS.TAXDIST,
  PS.CITYNAME,
  A.SALEDT,
  NVL(A.PRICE, 0) AS PRICE,
  -- SALEKEY: This parcel's key + additional parcels' keys from the SAME sale
  -- Also exclude voided conveyances
  CASE 
    WHEN A.NOPAR = 1 THEN TO_CHAR(A.SALEKEY)
    ELSE A.SALEKEY || NVL((
      SELECT ', ' || LISTAGG(S2.SALEKEY, ', ') WITHIN GROUP (ORDER BY S2.SALEKEY)
      FROM SALES S2
      LEFT JOIN CVTRAN CV2 ON CV2.CONVEYNO = S2.TRANSNO
      WHERE S2.SALEDT = A.SALEDT
        AND S2.SALEVAL = 'P'
        AND S2.PARID <> PS.PARID
        AND S2.NOPAR = A.NOPAR
        AND S2.PRICE = A.PRICE
        AND (CV2.CONVSTAT IS NULL OR CV2.CONVSTAT <> 'V')
    ), '')
  END AS SALEKEY,
  A.NOPAR,
  A.OLDOWN,
  A.OWN1,
  D.CARD,
  NVL(D.STORIES, 0) AS STORIES,
  D.STYLE,
  D.YRBLT,
  D.EFFYR,
  NVL(D.RMBED, 0) AS RMBED,
  NVL(D.RMFAM, 0) AS RMFAM,
  NVL(D.FIXBATH, 0) AS FIXBATH,
  NVL(D.FIXHALF, 0) AS FIXHALF,
  NVL(D.FIXADDL, 0) AS FIXADDL,
  D.BSMT,
  D.HEAT,
  D.FUEL,
  NVL(D.RECROMAREA, 0) AS RECROMAREA,
  NVL(D.FINBSMTAREA, 0) AS FINBSMTAREA,
  NVL(D.UFEATAREA, 0) AS UFEATAREA,
  NVL(D.WBFP_O, 0) AS WBFP_O,
  NVL(D.SFLA, 0) AS SFLA,
  D.GRADE,
  D.CDU,
  NVL(D.PCTCOMPLETE, 0) AS PCTCOMPLETE,
  NVL(D.RMLIV, 0) AS RMLIV,
  NVL(D.USER11, 0) AS USER11,
  AD.LOWER_LIST,
  AD.AREA_TOTAL,
  NVL(D.RECROMAREA, 0) + NVL(D.FINBSMTAREA, 0) + NVL(D.UFEATAREA, 0)
  + NVL(AD.ADDN_FIN_BSMT_AREA, 0) AS TOTAL_BASEMENT_FIN
FROM CAMAvsMLS PS
JOIN UniqueSales A
  ON A.PARID = PS.PARID
JOIN DWELDAT D
  ON D.PARID = PS.PARID
 AND D.TAXYR = PS.TAXYR
LEFT JOIN (
  SELECT
    PARID,
    TAXYR,
    LISTAGG(LOWER, ', ') WITHIN GROUP (ORDER BY LOWER) AS LOWER_LIST,
    SUM(CASE WHEN LOWER IS NOT NULL THEN AREA ELSE 0 END) AS AREA_TOTAL,
    SUM(CASE WHEN LOWER IN ('FBF', 'FBP', 'FBW') THEN AREA ELSE 0 END) AS ADDN_FIN_BSMT_AREA
  FROM ADDN
  WHERE CUR = 'Y'
  GROUP BY PARID, TAXYR
) AD
  ON AD.PARID = PS.PARID
 AND AD.TAXYR = PS.TAXYR
ORDER BY PS.PARID, A.SALEDT;